group:
# files to be synced
  - files:
      - source: .github
        dest: .github
        deleteOrphaned: true # Removes deleted files
      - source: .github/CODEOWNERS
      - source: .github/dependabot.yml
      - source: .github/FUNDING.yml
      - source: .github/labels.yml
      - LICENSE
      - favicon.ico
      - source: .packager/
        dest: .packager/
    repos: |
      N6REJ/AdiBags_Queens_Conservatory
      N6REJ/AdiBags_Shadowlands_Blacksmithing
      N6REJ/AdiBags_Shadowlands_Cooking
      N6REJ/AdiBags_Shadowlands_Engineering
      N6REJ/AdiBags_Shadowlands_Herbs
      N6REJ/AdiBags_Shadowlands_Inscription
      N6REJ/AdiBags_Shadowlands_Leatherworking
      N6REJ/AdiBags_Shadowlands_Mining
      N6REJ/AdiBags_Shadowlands_Tailoring
      N6REJ/Adibags_Shadowlands_Alchemy
      N6REJ/Adibags_Shadowlands_Enchanting
      N6REJ/Adibags_Shadowlands_Fishing
      N6REJ/Adibags_Shadowlands_Jewelcrafting
      N6REJ/Bears_audio_switcher
