# This is a basic workflow to help you get started with Actions

name: Package and Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # "release" here can be anything in one word
  release:

    # we can run our steps on pretty much anything, but the "ubuntu-latest" image is a safe bet
    runs-on: ubuntu-latest

    # specify the environment variables used by the packager, matching the secrets from the project on GitHub
    env:
      #CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.OAUTH }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

    # "steps" holds a list of all the steps needed to package and release our AddOn
    steps:

      # we first have to clone the AddOn project, which is simple enough, and is a required step
      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # once cloned, we just run the GitHub Action for the packager project
      - name: Package and Release
        uses: BigWigsMods/packager@master

